- 이지우/BJ_1477_휴게소세우기.java
이분탐색으로 풀었다.
맞게 풀었는데 자꾸 틀렸다고 나와서 열받은 문제다
결과적으로 풀지 못했는데
80%대에서 [런타임 에러 (ArrayIndexOutOfBounds)] 로 실패하는데
이유를 도저히 모르겠다..
잘푼거 같은데.. 혹시 이유를 아신다면 알려주세요 ㅜㅜ
> fail : BJ_1477_휴게소세우기

- 이지우/BJ_2606_바이러스.java
그래프 이론의 기초적인 문제였습니다.
저는 bfs로 해결하였고
1을 제외하고 방문한 좌표의 개수를 구했습니다.
쉬워서 설명은 생략하겠습니다.
> success : VJ_2606_바이러스

- 이지우/BJ_15998_카카오머니.java
정답률 10프로대로 생각할게 많은 문제였습니다.
1. 로그의 정확성 판별
2. 유클리드 호제로 통장에서 충당하는 금액 최대공약수 구하기
3. 1번의 조건을 만족하며 구해진 공약수가 로그 상 최소 가능한 충전금액보다 크다면 가능한 충전금액이 존재하므로 이때 최대공약수를 출력하면 됩니다
1번혹은 3번의 조건을 만족하지 못하면 -1을 출력합니다
또 로그에 입금만 있는 경우는 가능한 충전금액이 없다고 할 순 없으므로 1을 출력해주어 문제를 해결했습니다.
> ✅ success: boj 15998 카카오머니

- 이지우/BJ_1003_피보나치함수.java
- 이지우/BJ_2098_외판원순회.java
동적계획법에 대한 이해를 높여주는 문제였습니다.
외판원 순회 알고리즘은 아직도 연구중이고 꽤 중요한 알고리즘이라고 하니 한번 보고 약간의 이해정도 해두면 좋을꺼 같습니다.
풀이법 및 이해
1. 순환경로를 구하는 것임을 이해해야합니다.
예를 들어 목적지가 5가지 있을때 (1,2,3,4,5)
1-2-3-4-5-1
5-1-2-3-4-5
의 비용은 같습니다. 한가지 경로로 모든점들이 이어집니다.
이말은 아무점에서나 dfs해서 최단경로를 구하면 전체의 최단경로임을 의미합니다.
2. 동적계획법을 뒤에서 붙어 쌓아나가야합니다.
0을 시작으로 뒀다고 가정할때 0이 마지막일것입니다.
그렇다면 마지막 경로는
x -> 0
이고 이 값을 dp에 쌓습니다.
그 뒤 단계적으로
y -> x-> 0의 값을 쌓습니다. 그럼 다시 탐색할 필요가 없습니다.
!! 지금거쳐온 점들이 같고 현재 위치한 점이 같으면 그뒤에 경로의 최솟값은 같으므로 구해놓은 값을 써야 시간초과를 벗어납니다.
3. 비트마스킹을 써야합니다.
어떤 점을 갔는지가 중요하므로 거쳐온 점들을 비트마스킹으로 쌓아나갑니다.
쉽지 않은 문제였어요
> ✅ success: boj 2098 외판원순회 & ✅ success: boj 1003 피보나치함수

- 이지우/BJ_10159_저울.java
저의 풀이법
1. dp행렬 생성해서 관계가 있으면 크면 1 작으면 2로 셋팅
2. 플로이드 와샬
3. dp에 관계가 형성되지 않은것 카운트에서 값 출력
> ✅ success: boj 100159 저울

- 이지우/BJ_1507_궁금한민호.java
풀이법
1. A -> C 로 갈때 거리가 Z
A -> B  = X
B -> C  = Y
일때   X + Y = Z 라면     A 에서 C로 가는 도로는 없어도 된다
2. 불가능한 경우 -1 출력하라는게 좀 애매한데 주어진 그래프가 최소경로가 아닌경우 -1을 출력하는걸로 이해하는게 맞습니다.
> ✅ success: boj 1507 궁금한 민호

- 이지우/BJ_1516_게임개발.java
위상정렬을 통해 풀었습니다.
저는 클래스를 만들어서 했는데
그냥 리스트로 만들어서 하는게 빠른것 같습니다
> ✅ success: boj 1516 게임개발

- 이지우/BJ_1504_특정한최단경로.java
다익스트라로 세개의 정점에 대해서 최소거리배열을 구한 뒤
각 정점
1 <- 시작
A, B <- 경유
N <- 도착
라고 할때
1 -> A -> B -> N
1 -> B -> A -> N
두개의 값 중 작은값이 답이 됩니다.
> ✅ success: boj 1504 특정한최단경로

- 이지우/BJ_9370_미확인도착지.java
해당 간선을 통해 최단거리가 구해졌는지를 봐야합니다.
간선크기에 *2를 해 짝수로 만든뒤
해당 간선만 -1을 하게 되면
해당 간선을 경유했을 경우만 결과 값이 홀수가 될것입니다.
이 아이디어를 이용하면 한번데 다익스트라로 쉽게 풀 수 있습니다.
> ✅ success: boj 9370 미확인도착지

- 이지우/BJ_2250_트리의높이와너비.java
중위 순위를 통해 같은 depth의 최대 넓이를 구하는 문제였습니다.
1이 루트 노드가 아닐 수 있으므로 처음 union-find기법을 활용해 parents 배열을 만들어 루트노드를 찾고
inOrder 알고리즘을 돌리면 문제를 효율적으로 해결할 수 있습니다.
> ✅ success: boj 2250 트리의 높이와 너비

- 이지우/BJ_1016_제곱ㄴㄴ수.java
에라토스테네스의 체로 거른 뒤 소수의 제곱근들만 활용해서
해당 문제해결을 해야합니다.
중요한점은 범위가 1조이지만 start와 end는 백만으로 명시 되어서 그냥 범위내로 돌리지 않고
제곱근에 따른 시작점과 끝점을 정해서 반복문을 돌려야 시간초과에서 벗어날 수 있습니다.
long type 깜빡하지 않는다면 한번에 정답이 가능할꺼 같습니다.
> ✅ success: boj 1016 제곱ㄴㄴ수

- 이지우/BJ_2718_타일채우기.java
많이 어려웠습니다. 최근 푼 문제중에 가장 오랜걸린 문제입니다.
이 문제를 설명하기 위해선 그림이 필수 입니다.
그래서 스스로 제 풀이법을 설명드리긴 힘들것 같고
잘설명되어 있는 사이트를 찾아서 걸어놓았습니다. 해결이 안될경우 아래 링크를 참고하세요
[참고 사이트](http://joonas-yoon.blogspot.com/2016/03/2718.html)
> ✅ success: boj 2718 타일채우기

- 이지우/BJ_3190_뱀.java
뱀의 꼬리와 머리를 조정해 얼마나 갈 수 있는지 측정하면 되는 문제였습니다.
저같은 경우는 데큐를 써서 해결했습니다.
쉬운 문제이므로 따로 설명은 안하겠습니다.
> ✅success: boj 3190 뱀

- 이지우/BJ_15649_N과M_1.java
- 이지우/BJ_15649_N과M_2.java
- 이지우/BJ_15649_N과M_3.java
저번 코테에서 순열 조합 관련 심화 문제가 나왔는데 생각보다 어려워서
기초부터 다시 다지기 위해 풀었습니다.
1번은 순열
2번은 조합
3번은 중복순열
내일 중에 N 과 M문제 유형을 다 풀 예정입니다.
> ✅success: boj N과M 1~3

- 이지우/BJ_15649_N과M_4.java
- 이지우/BJ_15649_N과M_5.java
- 이지우/BJ_15649_N과M_6.java
- 이지우/BJ_15649_N과M_7.java
- 이지우/BJ_15649_N과M_8.java
- 이지우/BJ_15649_N과M_9.java
4. 중복 조합
5. 정해주는 값에 대한 순열
6. 정해주는 값에 대한 조합
> ✅success: boj N과M 4~6

- 이지우/BJ_15649_N과M_10.java
- 이지우/BJ_15649_N과M_11.java
- 이지우/BJ_15649_N과M_12.java
> ✅success: boj N과M 10~12

- 이지우/BJ_2143_두배열의합.java
투포인터, 이분탐색, 해쉬로 풀 수 있습니다.
저는 투포인터 와 이분탐색으로 풀었는데
둘다 시간이 상당히 길게 나옵니다
제소스에선
투포인터가 이분탐색보다 조금 빠르게 나왔습니다.
해쉬는 다른 사람 풀이를 보고 확인을 했는데 제일빠르고 제일 쉬웠습니다.
역시 중복값의 개수 파악은 해쉬가 짱입니다.
> ✅success: boj 2143 두배열의합

- 이지우/BJ_1715_카드정렬하기.java
이건 왜 골드4문제인지 잘모르겠습니다. 실버정도인거 같은데
그냥 우선순위큐에 넣고 더하고 넣고하면 풀리는 문제입니다
> ✅success: boj 1715 카드정렬하기

- 이지우/BJ_1520_내리막길.java
깊이 탐색 문제였습니다. 그냥 짜게 되면 시간초과가 나기때문에 DP를 쌓아가야합니다.
이론적으로 설명하면
도착지에서 가까운 점들부터 도착지로 갈 수 있는 방법을 쌓아나고 최종적으로 모두 합산해 시작점에서 갈 수 있는 방법이 구해지는 것입니다.
재미있는 문제입니다.
> ✅ success: boj 1520 내리막길

- 이지우/BJ_2623_음악프로그램.java
전형적인 위상정렬문제입니다. 따로 설명이 필요 없을것 같습니다.
> ✅ success: boj 2623 음악프로그램

- 이지우/BJ_2842_집배원한상덕.java
플레5 문제입니다. 솔빙하는데 시간이 좀 걸렸습니다
지정된 구간을 모두 돌 수 있는 최소 최대 높이의 차의 최솟값을 구하는 문제이기 때문에
투포인터를 활용해 구간을 지정한 후 해당 구간으로 dfs 또는 bfs를 돌리고 지정된 구간을 모두 돌았는지를 확인하며
최솟값을 구하는 문제입니다.
> ✅ success: boj 2842 집배원한상덕

- 이지우/BJ_11000_강의실배정.java
> ✅ success: boj 11000 강의실 배정

- 이지우/BJ_1941_소문난칠공주.java
접근을 잘못하면 어려워질 수 있는 문제입니다.
저도 더 잘풀어보려다가 미궁에 빠졌는데
그냥 간단하게 25개 중 7개를 뽑는 조합을 구한 뒤
이 조합이 문제의 조건에 맞는지 검사해 가능한 개수를 늘려나가면 됩니다.
> ✅ success: boj 1941 소문난칠공주

- 이지우/BJ_6087_레이저_통신.java
일반적인 bfs에서 같은조건이거나 나은조건이면 중복으로 돌아야한다는걸 생각해야 푸는 문제입니다.
visited 처리를 꺽는 횟수로 제한해서 풀면 됩니다.
> ✅ success: boj 6087 레이저

- 이지우/BJ_1647_도시분할계획.java
- 이지우/BJ_2211_네트워크복구.java
다익스트라 문제였습니다.
한점에서 다른 점으로 갈 수 있는 최소값을 구한는 것은 다른 문제들과 동일하지만
어떤 간선을 활용했는지를 알아야하는 문제기 때문에
해당점으로 최솟값이 적용되어 선택할때 배열에 넣고 기억한 뒤
다익스타라가 다 돌아간 뒤에 출력하여 해결했습니다.
> ✅ success: boj 2211 네트워크복구

- 이지우/BJ_2869_달팽이는올라가고싶다.java
- 이지우/BJ_4673_셀프넘버.java
1. 셀프넘버 풀이
- 제 풀이법은 에라토스테네스처럼 순차적으로 걸렀습니다.
- 더 좋은 풀이법은 한번씩 다돌리면서 딱 한단계의 뎁스만 걸러줍니다. 기본적으로 증가하는 경우밖에 없기 때문에 범위내의 모든 수를 한번씩만 봐줘도 전부 다 확인이 가능합니다.
2. 달팽이는 올라가고 싶다.
- 마지막에 미끄러지는 길이를 미리 뺍니다. 마지막은 미끄러질 일이 없기 때문에 미리 빼도 됩니다.
- 그러면 해당 위치에 도달하거나 넘어서면 됩니다. 남은 길이를 하루에 올라가는 길이로 나눠 답을 구하면 됩니다.
> ✅ success: boj 4673 셀프넘버 && ✅ success: boj 2211 달팽이는올라가고싶다

- 이지우/BJ_9527_1의개수세기.java
정말 스트레스 받게 하는 문제입니다.
규칙을 알아야 풀 수 있는 문제인데 규칙 자체는 한번 비트를 쭉 그려보면 찾기 쉽습니다.
하지만 규칙을 알아도 1<<32 == 1<<0 와 같이 int로 처리되므로 1L<<32 이런식으로 처리하는 등의 에러가 저는 더 어려웠습니다.
> success: boj 9527 1의개수세기

- 이지우/BJ_20040_사이클게임.java
유니온 파인드를 활용하면 쉽게 풀리는 문제입니다.
레벨처리하여 유리하게 합쳐주시고
유니온 파인드 적용으로 끝나는 문제라 따로 설명이 없습니다.
> ✅ success: boj 20040_사이클

- 이지우/BJ_1041_주사위.java
골드5치고 쉽지 않았습니다.
우선 공식을 생각해내야합니다. 
공식은 맨위, 두번째부터 바닥으로 구간을 나누어 하면 됩니다.
여기까지는 1트에 했는데
주사위 이므로 제한되는 경우가 있음을 생각해
모든 경우를 다 돌려야했습니다.
> ✅ success: boj 1041 주사위

- 이지우/BJ_2467_용액.java
투포인트와 이분탐색 둘 중 하나를 사용하면 해결되는 문제입니다.
이문제 같은 경우는 투포인트가 조금 더 빨랐습니다.
> ✅ success: boj 2467 용액

- 이지우/BJ_9318_열쇠.java
가장자리 테두리를 하나 더 만들고 마스킹하며 bfs하면 쉽게 풀리는 문제입니다.
> ✅ success: boj 9318 열쇠

- 이지우/BJ_10942_펠린드롬.java
디피 문제로 모든 경우의 펠린드롬을 판별을 한 후 답을 출력하면 되는 문제입니다.
길이가 1~2까지를 쌓은 뒤
그 후 i~j가 팰린드롬인지 확인하려면 num[i] == num[j] 와  dp[i+1][j-1] == 1을 만족하는지로 판별할 수 있습니다.
> ✅ success: boj 10942 펠린드롬

- 이지우/BJ_2166_다각형의면적.java
수리 문제입니다.
신발끈 공식을 써서 풀어야합니다.
공식을 이용하지 않으면 매우 어려워집니다.
> ✅ success: boj 2166 다각형의 면적

- 이지우/BJ_1799_비숍.java
백트랙킹 문제로 가지를 쳐가는 문제입니다.
우선 대각선으로만 가는 특성으로 짝수좌표와 홀수좌표로 한번 나누어 줄이고
각각 둘 수 있는 최대를 합쳐서 구하는 문제입니다.
저도 솔빙은 했지만 저는 visited이차원 배열을 만들어 해당 좌표에 비숍을 둘 때마다 visited 배열을 갱신해주어 둘 수 있는지 판단하여 재귀함수를 돌렸는데
이보다 훨씬 나은 방법은 대각선 두 방향을 정의하는 것입니다.
왼쪽 상단에서 우측 하단으로 내려가는 직선은 y-x가 같으면 같다고 판단할 수 있고
우측 상단에서 좌측 하단으로 내려가는 직선은 y+x가 같으면 같다고 판단할 수 있습니다.
> ✅ success: boj 1799 비숏

- 이지우/BJ_9095_123더하기.java
dp 문제입니다.
식은 dp[n] = dp[n-1] + dp[n-2] + dp[n-3]
입니다
이유는
dp[x]의 경우는 1, 2, 3 만 쓸 수 있으므로 아래와 같이 세 경우가 가능하며
(x-1) + 1   =   dp[n-1] 
(x-2) + 2   =   dp[n-2] 
(x-3) + 3   =   dp[n-3]
다음과 같기 때문입니다.
> ✅ success: boj 9095 1,2,3 더하기

- 이지우/BJ_9375_패션왕신해빈.java
처음에는 subSet으로 모든 경우를 구해서 더했는데
그럴 필요없이 종류별로 곱하면 되는데
두가지 종류가 a, b개 있다면
a+1 * b+1 -1 이 답입니다.
> ✅ success: boj 9375 패션완신해빈

- 이지우/BJ_9461_파도반수열.java
규칙을 찾아서 dp를 쌓는 간단한 문제입니다.
범위가 int를 넘길줄 몰랐는데 넘겨서 당황한거 말고는 매우 쉬웠습니다.
> ✅ success: boj 9461 파도반 수열

- 이지우/BJ_1509_팰린드롬분할.java
먼저 팰린드롬인 경우를 모두 구해야합니다.
boolean palin[start][end] -> 시작과 끝을 정해줘서 해당 구간이 팰린드롬인지 모두 구합니다.
size가 1,2인경우를 미리 셋팅한 다음에
3부터는 양끝이 같다면 그사이가 팰린드롬인지 판별해서 구할 수 있습니다.
모두 구했다면 dp를 해야 시간초과를 벗어날 수 있습니다.
paline[j][i] 가 true 이면 해당구간은 팰린드롬입니다.
따라서
dp[i] = Math.min(dp[j-1]+1, dp[i])
점화식으로 dp를 쌓아 나가고
결국 dp[len]이 답이 됩니다. len은 주어진 문자열의 길이입니다.
> ✅ success: boj 1509 팰린드롬분할

- 이지우/BJ_16724_피리부는사나이.java
- 이지우/BJ_4386_별자리만들기.java
프림으로 풀었습니다.
최소 스패닝 트리 문제인거 같아서 프림과 크루스칼중 고민을 했는데
N은 100이고 간선의 개수는 N(N-1)/2 라서 N^2/2라 제한조건이 널널해  멀하든 상관 없었지만
그래도 정점이 비교적 더 적다고 판단되어 프림으로 풀었습니다.
우선 점들간의 거리를 모두 구했고 임의로 한 정점을 넣은 후 우선수위 큐에 간선을 넣어서 돌리는 식으로 하여 모든 정점을 방문하고 이때 최솟값을 뽑아내서 해결했습니다.
> ✅ success: boj 4386 별자리만들기

- 이지우/BJ_16946_벽부수고이동하기4.java
- 이지우/BJ_2473_세용액.java
저는 이분 탐색으로 해결했습니다.
이중 포문을 돌려 왼쪽과 가운데 값을 고정한 뒤 나머지 오른쪽 부분을 이분탐색을 해서 해결했습니다.
더 효율적인 방법은 투포인터로
왼쪽값만 고정시키고 가운데=왼쪽+1 오른쪽=N-1로 시작해 값에따라 가운데++ 오른쪽--를 통해 가장 0에 가까운 값을 찾는 방법입니다.
이분탐색은 O(N*N*logN)
투포인터는 O(N*N)
인거 같습니다.
> ✅ success: boj 2473 세용액

- 이지우/BJ_1197_최소스패닝트리.java
크루스칼로 풀었습니다.
모든 간선을 우선순위 큐로 넣어줘서 O(NlogN)의 복잡도로 했고
큐를 모드 돌아주면 작은값부터 union_find 해주어 union될떄만 가중치를 더해 답을 구했습니다.
> ✅ success: boj 1197 최소스패닝트리

- 이지우/BJ_11404_플루이드.java
전형적인 플루이드 와샬 문제입니다.
주의할점은 못가는 경우 0으로 표시하라는 것입니다.
INF값으로 지정한값보다 같거나 크면 (사실 오버플로우만 없다면 큰 경우는 없을것입니다) 0으로 표시하면 됩니다.
> ✅ success: boj 11404 플루이드

- 이지우/BJ_16236_아기상어.java
조건처리를 잘하면 됩니다.
제가 실수한 부분을 정리하면
1. 이동거리를 x축차이와 y축차이를 더한거라고 생각했는데 돌아가야하는 경우를 생각 못했습니다. depth값을 넣어서 해결했습니다.
2. '거리가 가까운 물고기가 많다면, 가장 위에 있는 물고기, 그러한 물고기가 여러마리라면, 가장 왼쪽에 있는 물고기를 먹는다'
상좌우하로 돌리면 위 조건에 만족할 꺼라고 생각했는데 아니었습니다. 저는 그래서 같은 뎁스까지는 봐서 위조건에 만족하는 인덱스값을 뽑아내서 그 위치로 가게 했는데
풀고 난 후 더 좋은 방법은 우선순위큐로 애초에 해당 조건에 부합하게 정렬했으면 더 좋았다고 떠올랐습니다.
> ✅ success: boj 16236 아기상어

- 이지우/BJ_1922_네트워크연결.java
크루스칼과 프림 둘다 모두 풀어봤습니다.
모두 수 N (1 ≤ N ≤ 1000)가 주어진다.
선의 수 M (1 ≤ M ≤ 100,000)가 주어진다.
위의 경우 프림이 더 빨랐습니다. 이떄 크루스칼과 큰 차이가 없었으므로
위 기준으로 노드가 감소하거나 선의 수가 증가할때는 프림
반대로 노드가 증가하거나 선의수가 감소하면 그때는 크루스칼이 유리할것 같습니다.
천십만프림크루스칼이라고 외워두려합니다.
> ✅ success: boj 1922 네트워크연결

- 이지우/BJ_2887_행성터널.java
저는 측정된 난이도 치고는 꽤 쉽게 풀었던 문제입니다.
점사이의 거리가 min(|xA-xB|, |yA-yB|, |zA-zB|)로 구하도록 명시되어
주어지는 3차원 좌표를 x y z따로 세개의 우선순위 큐로 잡아 nlogn의 시간복잡도로 정렬 시킨뒤
순서대로 사이거리를 구해 한개의 원순위 큐에 넣어줬습니다.
그뒤 unionfind로 N-1개의 간선을 합쳐 선택한 간선의 거리의 합은 도출했습니다.
크루스칼입니다. 천(노드 개수)십만(간선 개수)기준으로 프림,크루스칼이 갈린다고 생각하는데
노드를 나타내는 천이 십만으로 증가했기때문에 크루크칼이 유리합니다.
> ✅ success: boj 2887 행성터널

- 이지우/BJ_12852_1로만들기2.java
처음에 탐욕법이나 수학으로 접근해서 힘들었습니다.
결국에는 모든 경우를 다 가면서 유리한 상황을 택하는 그래프이론이였습니다.
저는 깊이탐색으로 풀었습니다.
무조건 3과 2로 나누는 경우를 모두 탐색해 더 유리한 경우만 가지를 쳐서 이었습니다.
나머지 처리도 포함시켰습니다.
더 효율적인 풀이방법은 넓이 탐색입니다.
처음 값에서 시작해 나눠지는 경우만 큐에 넣어줍니다.
이떄 유리한점은 cnt 비교를 안해도 되는 점과 나눠지는 경우만 로직이 돌아가는 부분인것 같습니다.
cnt 비교를 안하는 이유는 넓이 탐색이기 때문에 나중에 들어오는 값이 무조건 클 수 밖에 없기 때문입니다.
> ✅ success: boj 12852 1로만들기2

- 이지우/BJ_1541_잃어버린괄호.java
그리디 였습니다.
결국 - 가 있다면 그 뒤의 수는 모두 뺄 수 있다는걸 깨달았고
그다음은 문자열, 파싱의 문제 였습니다.
StringTokenizer를 썻으면 좀 더 좋았을 문제입니다.
> ✅ success: boj 1541 잃어버린괄호

- 이지우/BJ_1620_나는야포켓몬마스터이다솜.java
- 이지우/BJ_1780_종이의개수.java
종이의 개수 문제는 분할 정복이었습니다.
먼저 가장 큰 네모를 탐색해 모두 같은지 판별했고
같다고 해당영역은 그것으로 종료이며
모두 같지 않다면 해당영역을 3*3으로 분할하여 반복하였습니다.
> ✅ success: boj 1780 종이의 개수

- 이지우/BJ_1764_듣보잡.java
- 이지우/BJ_1927_최소힙.java
- 이지우/BJ_2630_색종이만들기.java
> ✅ success: boj 1764 듣보잡 && 2630 색종이만들기

- 이지우/BJ_1958_LCS3.java
3개 문자열의 공통수열입니다.
3차원을 그려봐야합니다. 모든 낱말이 일치할 경우 전단계(3가지 요소가 모두 현재 인덱스보다 작음)에 +1을 해서 dp를 쌓아간다고 생각하면 쉽습니다.
모두 일치하지 않은경우는 현재 누적치는 기록해야하므로 바로 전단계 한요소에 -1을 뺸 세가지 요소의 가장 큰 값을 가져와서 쌓으면 됩니다.
결국 3차원 행렬의 마지막 값이 답이 됩니다.
> ✅ success: boj 1958 LCS 3

- 이지우/BJ_11727_2n타일링2.java
- 이지우/BJ_17626_FourSquares.java
최대 4개의 제곱수의 덧셈으로 모든 자연수를 만들 수 있다.
dp문제입니다.
1부터 N까지 차례로 쌓아가는 bottom up 방식의 문제로
i차례일때 i보다 작은 모든 제곱수를 빼서 확인합니다.
그 수를 j라 했을때 j*j라고 정의가 되고 i -j*j는 이미 구한 dp인덱스 값입니다. 그 수의 최소 제곱근 개수를 뜻합니다.
그러므로 모든 제곱수를 돌면 
```
dp[i] = Math.min( dp[i] , dp[i-j*j]+1 )
```
라는 점화식으로 풀 수 있습니다.
> ✅ success: boj 17626 fourSquare

- 이지우/BJ_11724_연결요소의개수.java
조합론 문제였습니다.
visit으로 풀어도 되지만 union-find가 더 좋은것 같습니다.
저는 마지막 요소파악을 set으로 중복을 제거해서했지만
유니온하면서 유니온되는 횟수를 측정해 더 빨리 할 수 있는법이 존재합니다.
저도 이부분을 몰라서 습득했습니다.
> ✅ success: boj 11724 연결요소의개수

- 제진명/nov2022/Main_boj_21609_상어중학교.java
> ✅ success: boj 21609 상어중학교

- 이지우/BJ_2662_이중우선순위큐.java
TreeMap을 처음 제대로 써본것 같습니다.
Entry라는 것을 처음 써봤는데 poll하면 map에서도 동시에 같이 빠집니다 다른 객체이지만 기능적으로 연결이 된것 같습니다. 내부 소스를 보지 못했지만 신기한것 같습니다.
map에 숫자를 넣는 과정에서
```
if(map.containsKey(num)) {
map.put(num, map.get(num)+1);
}else map.put(num,1);
```
이런식으로 중복되면 갯수를 추가하는 식으로 했는데
```
map.merge(num, 1, (v1, v2) -> v1 + v2)
map.merge(key, value, (v1, v2) -> v1 + v2)
```
가 더 나은 함수인 것 같습니다. 키가 중복될 경우 더한다는 의미입니다.
그리고 이 함수는
```
map.merge(num, 1, Integer::sum)
```
와 같습니다.
람다를 날잡고 공부해야 될 것 같습니다.
> ✅ success: boj 2662 이중우선순위큐

- 이지우/BJ_1107_리모컨.java
> ✅ success: boj 1107 리모컨

- 제진명/nov2022/Main_boj_13460_구슬탈출2.java
bfs로 빨간 구슬과 파란 구슬을 4방향으로 이동시킨 후 빨간 공과 파란 공의 위치를 비교하여 빨간 공만 홀에 들어간 경우의 최소 이동 횟수를 구함.
> ✅ success: boj 13460 구슬탈출2

- 이지우/BJ_16953_AtoB.java
> ✅ success: boj 16953 A->B

- 제진명/jenuary2023/Main_boj_11582_치킨TopN.java
- 제진명/jenuary2023/Main_boj_24460_특별상이라도받고싶어.java
✅ success: boj 24460 특별상이라도 받고 싶어
> ✅ success: boj 11582 치킨 Top N
